package DataRecords;

/*
 * Enum type representing city names
 */
public enum CityName {
	BOSTON, NEWYORKCITY, PHILADELPHIA, BALTIMORE, WASHINGTON, 
	CHARLOTTE, ATLANTA, PITTSBURGH, COLUMBUS, INDIANAPOLIS, 
	STLOUIS, KANSASCITY, DENVER, OKLAHOMACITY, DALLAS, HOUSTON,
	NEWORLEANS, MEMPHIS, JACKSONVILLE, NASHVILLE, CHICAGO, MINNEAPOLIS, 
	SALTLAKECITY, LASVEGAS, LOSANGELES, SANFRANCISCO, PORTLAND, SEATTLE,
	PHOENIX, ALBUQUERQUE, SANANTONIO, MIAMI;
}
